services:
  backend:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRED: ${JWT_ACCESS_TOKEN_EXPIRED}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run migration:run && npm run start:prod"


  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3307:${DB_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

# docker-compose sẽ tạo với prefix docker_ (tên thư mục chứa docker-compose.yml)